#!/usr/bin/env zsh

#autoload
# Reset chezmoi state, re-init, pull, then apply to re-run scripts.

function chezmoi-rerun() {
  emulate -L zsh
  set -o errexit

  chezmoi state reset --force
  chezmoi init
  chezmoi apply
}
