{{ if eq .chezmoi.os "windows" }}
["AppData/Local/nvim"]
{{ else }}
[".config/nvim"]
{{ end }}
  type = "git-repo"
  url = "https://github.com/AstroNvim/AstroNvim.git"
  refreshPeriod = "168h"

{{ if eq .chezmoi.os "windows" }}
["AppData/Local/nvim/lua/user"]
{{ else }}
[".config/nvim/lua/user"]
{{ end }}
  type = "git-repo"
  url = "https://github.com/drop-stones/astronvim_config.git"
  refreshPeriod = "168h"

[".oh-my-zsh"]
  type = "git-repo"
  url = "https://github.com/ohmyzsh/ohmyzsh.git"
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-autocomplete"]
  type = "git-repo"
  url = "https://github.com/marlonrichert/zsh-autocomplete.git"
  refreshPeriod = "168h"
[".oh-my-zsh/custom/plugins/zsh-proxy"]
  type = "git-repo"
  url = "https://github.com/SukkaW/zsh-proxy.git"
  REFRESHPERIOD = "168h"
