[display]
compact = false
use_pager = false

[style.description]
foreground = "white"

[style.example_text]
foreground = "green"

[style.command_name]
foreground = "blue"

[style.example_code]
foreground = "white"
bold = true

[style.example_variable]
foreground = "white"
underline = true

[updates]
auto_update = true
