[general]
import = ["tokyonight_night.toml", "keybind.toml", "shell.toml"]

[window]
padding = { x = 10, y = 10 }
decorations = "None"
opacity = 0.7

[font]
normal = { family = "0xProto Nerd Font", style = "Regular" }
size = 9.0

[debug]
log_level = "Error"
