# ~/.config/starship.toml

scan_timeout = 10
command_timeout = 10000

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[cmd_duration]
disabled = true

[container]
disabled = true
